image: node:16

stages:
  - conventions
  - stylelint
  - eslint

before_script:
  - npm install

cache:
  paths:
    - node_modules/

commit_convention:
  stage: conventions
  needs: []
  script:
    - npx --quiet commitlint --from="$CI_MERGE_REQUEST_DIFF_BASE_SHA" --help-url 'https://raccoongang.atlassian.net/wiki/spaces/PSC/pages/2662006787/RG+Delivery+Solutions+Conventional+Commits'
  rules:
    - if: "$CI_MERGE_REQUEST_EVENT_TYPE != 'merge_train' && $CI_MERGE_REQUEST_DIFF_BASE_SHA"

stylelint:
  stage: stylelint
  script:
    - npm run lint-style
  only:
    - merge_requests

eslint:
  stage: eslint
  script:
    - npm run lint
  only:
    - merge_requests
