#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

Color_On='\033[106m'     # Cyan Color
Color_Off='\033[0m'      # Color Reset

echo "${Color_On}Run: commitlint${Color_Off}" && npx --no -- commitlint --edit
